USE flash_quiz_dev_db;
INSERT INTO category (name) VALUES ('General Knowledge');
INSERT INTO category (name) VALUES ('Science');
INSERT INTO category (name) VALUES ('History');
INSERT INTO category (name) VALUES ('Geography');
INSERT INTO category (name) VALUES ('Art');
INSERT INTO category (name) VALUES ('Sports');
INSERT INTO category (name) VALUES ('Music');
INSERT INTO category (name) VALUES ('Movies');
INSERT INTO category (name) VALUES ('Literature');
INSERT INTO category (name) VALUES ('Technology');
INSERT INTO category (name) VALUES ('Nature');
INSERT INTO category (name) VALUES ('Food');
INSERT INTO category (name) VALUES ('Animals');
INSERT INTO category (name) VALUES ('Mythology');
INSERT INTO category (name) VALUES ('Politics');
INSERT INTO category (name) VALUES ('Religion');
INSERT INTO category (name) VALUES ('Vehicles');
INSERT INTO category (name) VALUES ('Games');
INSERT INTO category (name) VALUES ('Fashion');
INSERT INTO category (name) VALUES ('Comics');
INSERT INTO category (name) VALUES ('Anime');
INSERT INTO category (name) VALUES ('Cartoons');
INSERT INTO category (name) VALUES ('Manga');
INSERT INTO category (name) VALUES ('TV Shows');
INSERT INTO category (name) VALUES ('Celebrities');
INSERT INTO category (name) VALUES ('Internet');
INSERT INTO category (name) VALUES ('Books');
