USE flash_quiz_dev_db;
INSERT INTO category (id, name) VALUES (1, 'General Knowledge');
INSERT INTO category (id, name) VALUES (2, 'Science');
INSERT INTO category (id, name) VALUES (3, 'History');
INSERT INTO category (id, name) VALUES (4, 'Geography');
INSERT INTO category (id, name) VALUES (5, 'Art');
INSERT INTO category (id, name) VALUES (6, 'Sports');
INSERT INTO category (id, name) VALUES (7, 'Music');
INSERT INTO category (id, name) VALUES (8, 'Movies');
INSERT INTO category (id, name) VALUES (9, 'Literature');
INSERT INTO category (id, name) VALUES (10, 'Technology');
INSERT INTO category (id, name) VALUES (11, 'Nature');
INSERT INTO category (id, name) VALUES (12, 'Food');
INSERT INTO category (id, name) VALUES (13, 'Animals');
INSERT INTO category (id, name) VALUES (14, 'Mythology');
INSERT INTO category (id, name) VALUES (15, 'Politics');
INSERT INTO category (id, name) VALUES (16, 'Religion');
INSERT INTO category (id, name) VALUES (17, 'Vehicles');
INSERT INTO category (id, name) VALUES (18, 'Games');
INSERT INTO category (id, name) VALUES (19, 'Fashion');
INSERT INTO category (id, name) VALUES (20, 'Comics');
INSERT INTO category (id, name) VALUES (21, 'Anime');
INSERT INTO category (id, name) VALUES (22, 'Cartoons');
INSERT INTO category (id, name) VALUES (23, 'Manga');
INSERT INTO category (id, name) VALUES (24, 'TV Shows');
INSERT INTO category (id, name) VALUES (25, 'Celebrities');
INSERT INTO category (id, name) VALUES (26, 'Internet');
INSERT INTO category (id, name) VALUES (27, 'Books');
